# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ['src/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
       php: 7.3
       mysql: 5.5
       postgresql: true
       memcached: true
       mongodb: true
    tests:
            override:
                -
                    command: './vendor/bin/phpunit --coverage-clover=clover.xml'
                    coverage:
                        file: 'clover.xml'
                        format: 'clover'

    project_setup:
            before:
                - mysql -e "CREATE DATABASE linna_db"
                - mysql -u root linna_db < tests/linna_db_mysql.sql
