language: php
php:
- 7.4

services:
- mysql
- memcached
- mongodb
- postgresql

before_install:
## Add php extensions
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
## Update postgresql
- sudo apt-get update
- sudo apt-get --yes remove postgresql\*
- sudo apt-get install -y postgresql-11 postgresql-client-11 unzip
- sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
- sudo sed -i 's/5433/5432/g' /etc/postgresql/11/main/postgresql.conf
- sudo cat /etc/postgresql/11/main/postgresql.conf
- sudo service postgresql restart 11
- sudo cat /var/log/postgresql/postgresql-11-main.log
## Update sonar-scanner
- wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216.zip
- unzip sonar-scanner-cli-4.5.0.2216.zip -d /tmp

before_script:
- composer install
- psql -U postgres -a -f vendor/linna/db-dumps/src/linna_db_pgsql_test.sql
- mysql -e 'create database linna_db;'
- mysql -u root linna_db < vendor/linna/db-dumps/src/linna_db_mysql_test.sql

addons:
  sonarcloud:
    organization: "linna"

git:
  depth: false

script:
- ./vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
#- ./vendor/bin/infection --min-msi=75 --min-covered-msi=75
- /tmp/sonar-scanner-4.5.0.2216/bin/sonar-scanner